name = "Optimum"
author = "Levviata"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a91bec469a566f45a4f9d94cf82a9a86f9dc3fcf351b6993cdbf342246f35031"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
