name = "Optimum"
author = "Levviata"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4639cbc4227ba30e964b82dc5d4b27a72b80aa602be459e2948fae3c631af831"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
