name = "Optimum"
author = "Levviata"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ad1a20ae0dad8155e2835b0fd1b13eaae5cbdad7a6a547f2058b98958a060e2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
