name = "Optimum"
author = "Levviata"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49d5e87e0efec7e47bc32ff591e0bfdc3ece539b60df11ddf0f574d4590bbc26"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
