name = "Optimum"
author = "Levviata"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "421afbc5ef25d67af9d385db8046683707ad250c50c918070e6d6a9e3526f5f1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
