name = "Optimum"
author = "Levviata"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3e901833f6dc3910c9d9f453ea011d04ccb8d30d74c5a6fd559cefe72dd3074"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
