name = "Optimum"
author = "Levviata"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3624a1ff698f8522d0af7d516e7743cacb28bc3f7bc5c3036c7436501cf2a4ff"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
