name = "Optimum"
author = "Levviata"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0578e4d6cf9643a16d51f9787903bcbe4932f33eb60b78f192ee4ce79a0634dc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
