name = "Optimum"
author = "Levviata"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f816f4338e2feb4d20f0f06213e3cb5aadf9763a38bfa84918ffcbf208138a8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
