name = "Optimum"
author = "Levviata"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d07dd0eff2879d3e1efce791b417ced11626c504d9f9ac6f4de879e5ae1e9f45"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
