name: Build And Publish to CurseForge
on:
  workflow_dispatch:

jobs:
  build-curseforge:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Restore Packwiz cache
      - name: Restore Packwiz Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz
          key: packwiz-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            packwiz-${{ runner.os }}-

      # Get version number
      - name: Extract version using grep
        id: fetch_version
        run: |
          cd CurseForge
          VERSION=$(grep '^version' pack.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      # Make sure the folder exists, this is often redundant.
      - name: Create CurseForge folder
        run: mkdir -p CurseForge

      # Export curseforge pack
      - name: Export CurseForge files
        run: |
          cd CurseForge
          ~/.cache/packwiz/packwiz curseforge export -o Optimum-CurseForge-${{ env.version }}-beta.zip

      - name: Upload CurseForge Pack
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: "${{ secrets.CURSEFORGE_TOKEN }}"
          project-id: "1183185"
          modpack-path: "./CurseForge/Optimum-CurseForge-${{ env.version }}-beta.zip"
          changelog: "**Full Changelog**: https://github.com/Levviata/Levviatas-Optimization-Pack/releases/tag/v${{ env.version }}"
          changelog-format: "markdown"
          game-version: "1.12.2"
          display-name: "Optimum v${{ env.version }}-beta"
          release-type: "beta"